### ISSUE TITLE
Bug: Error: Plugin did not respond

### ISSUE THREAD

**Issue by lukemurraynz** [Azure/ALZ-PowerShell-Module#240]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

both

### Starter Module? (Required)

not relevant

### Expected Behaviour (Required)

PS C:\Code> Deploy-Accelerator
Getting ready to deploy the accelerator with you...
No input configuration file path has been provided. Please provide the path(s) to your configuration file(s)...

Checking you have the latest version of Terraform installed...
Although you have selected Bicep, the Accelerator leverages the Terraform tool to bootstrap your Version Control System and Azure. This is will not impact your choice of Bicep post this initial bootstrap. Please refer to our documentation for further details...

Checking and Downloading the bootstrap module...
The directory for .\bootstrap\v4.1.0 already exists and has content in it, so we are not overwriting it.
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azapi_v1.15.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x982b99]

goroutine 82 [running]:
github.com/Azure/terraform-provider-azapi/internal/clients.(*ResourceManagerAccount).GetTenantId(0xc0005c6850)
        github.com/Azure/terraform-provider-azapi/internal/clients/account.go:44 +0x139
github.com/Azure/terraform-provider-azapi/internal/services.(*ClientConfigDataSource).Read(0xc001620010, {0xee621c8, 0xc00151cb70}, {{{{0xee67000, 0xc00151d2c0}, {0xdc37c0, 0xc00151d230}}, {0xee69078, 0xc00150c7c0}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/Azure/terraform-provider-azapi/internal/services/azapi_client_config_data_source.go:79 +0x385
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0002451e0, {0xee621c8, 0xc00151cb70}, 0xc00151cc00, 0xc00158f6c8)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_readdatasource.go:79 +0x433
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0002451e0, {0xee621c8?, 0xc00151ca50?}, 0xc0016180a0)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_readdatasource.go:55 +0x41c
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0000c10e0, {0xee621c8?, 0xc00151c090?}, 0xc00042a050)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/tf6server/server.go:686 +0x416
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0xebc960?, 0xc0000c10e0}, {0xee621c8, 0xc00151c090}, 0xc001610000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c1200, {0xee621c8, 0xc00151c000}, {0xee67920, 0xc00050e1a0}, 0xc00011d560, 0xc00038e2d0, 0xf489ba0, 0x0)
        google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001c1200, {0xee67920, 0xc00050e1a0}, 0xc00011d560)
        google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 21
        google.golang.org/grpc@v1.62.1/server.go:1038 +0x135

Error: The terraform-provider-azapi_v1.15.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Terraform plan for apply failed with exit code 1. Please review the error and try again or raise an issue.
Exception: C:\Users\lukej\OneDrive\Documents\PowerShell\Modules\ALZ\4.1.0\Private\Deploy-Accelerator-Helpers\Invoke-Terraform.ps1:75
Line |
  75 |              throw "Terraform plan failed with exit code $exitCode. Pl …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Terraform plan failed with exit code 1. Please review the error and try again or raise an issue.

### Actual Behaviour (Required)

Terraform to run

### References (Optional)

I had retrieved this issue when running the Deploy-Accelerator locally. The fix was login to Azure first (using az login).

Can the login first be added to the documentation, and perhaps this issue referenced in the Troubleshooting wiki?

**Comment by jaredfholgate** [comment]
Hi. It is here in the docs. Does it need to be somewhere else? https://github.com/Azure/ALZ-PowerShell-Module/wiki/%5BUser-Guide%5D-Quick-Start-Phase-1#131-authenticate-via-user-account

Also we have an existing issue open to provide a more useful error message in this scenario here: https://github.com/Azure/ALZ-PowerShell-Module/issues/231

**Comment by lukemurraynz** [comment]
Maybe just add it as a reminder to the Quick Start here: https://github.com/Azure/ALZ-PowerShell-Module?tab=readme-ov-file

Quick Start
To get going right now, run these PowerShell steps:

Install-Module -Name ALZ
# If not logged into Azure first, make sure you do this (either with Connect-AzAccount or az login for Azure CLI).
Deploy-Accelerator
